[project]
org-name= "sasindu"
version= "0.1.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "postgresql-42.2.18"

    path = "/usr/share/doc/postgresql-12/postgresql-42.2.18.jar"

[dependencies]

